### ISSUE TITLE
<div _ngcontent-c4="" class="scrollable-content" style="transform: translateY(300px);">

### ISSUE THREAD

**Issue by francoro** [rintoj/angular2-virtual-scroll#115]
http://rintoj.github.io/angular2-virtual-scroll/#samples

In my case it doenst update the transform value when i scroll what iam missing?
i cant put it the [item] in the virtual-scroll child also y have to use a div not list-item it throw me a error that it can add that property to the div. I think the problem is around there

**Comment by speige** [comment]
list-item is a made up component simply used as an example in the documentation. You have to create your own child component.

You can use a <div> instead of a custom component, however you can't use [item]="" on a <div> because that attribute doesn't exist. Instead you should use something like:

```
<virtual-scroll [items]="items" (update)="viewPortItems = $event">
    <div *ngFor="let item of viewPortItems">{{item?.name}}</div>
</virtual-scroll>
```

Closing. Please re-open if you're still having issues.
