### ISSUE TITLE
scrollInto() animation ends before reaching target

### ISSUE THREAD

**Issue by simianarmy** [rintoj/angular2-virtual-scroll#125]
I have a large list with about 4 items per page, with images and other data.  When I try to use scrollInto to jump ahead many pages, the scrolling animation stutters and fails to reach the target item before the animation timer expires.
I see other perf improvement PRs here that might address this, but was wondering if there were any simple optimizations I could do to solve this

**Comment by rintoj** [comment]
It seems an issue with the child height and width. I am assuming that you get the same stutters as you scroll normally without using `scrollInto()`, the reason could be same.

**Comment by speige** [comment]
One solution might be to modify the animation time. I prefer 750, instead of the default 1500.

Another would be to simplify your component as much as possible & use OnPush change detection strategy instead of Default.

Aside from that, post a stackblitz of your problem so we can troubleshoot further.

There are some potential optimizations for angular2-virtual-scroll itself which we will hopefully do in the future, but it might be awhile. However, the main problem is more likely related to your code, since other users aren't experiencing this issue.

Closing for now. Re-open if you have a stackblitz to troubleshoot.
