### ISSUE TITLE
What is the local development story?

### ISSUE THREAD

**Issue by tstirrat** [rintoj/angular2-virtual-scroll#126]
I have tried to quickly iterate locally using the demo server, but it uses the published npm package, so changes to `src/virtual-scroll.ts` do not make it into the local server.

I tried using `npm link`, but it doesn't work:

```
cd angular2-virtual-scroll
npm link  # builds the dist folder

cd demo
npm link angular2-virtual-scroll  #links the live dev version into the demo

npm start

> demo@0.0.0 start /Users/tstirrat/dev/virtual-scroll-demo/demo
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **

<snip>

ERROR in /Users/tstirrat/dev/virtual-scroll-demo/src/virtual-scroll.ts (15,8): Cannot find module '@angular/core'.

ERROR in /Users/tstirrat/dev/virtual-scroll-demo/src/virtual-scroll.ts (17,24): Cannot find module '@tweenjs/tween.js'.
webpack: Failed to compile.
```

The only way that seems to work is push a branch to github, then set `demo/package.json` to use the github branch, and run `npm i` every time. This is painful.

What is your dev setup? Is there a way to iterate quickly on this so that changing `src/virtual-scroll.ts` updates automaticall in the local dev server?

And please put some instructions in the README.md or a CONTRIBUTING.md

Thanks!

**Comment by rintoj** [comment]
@tstirrat, Thanks for your contributions. 

I think this is difficult part of maintaining an angular component. I am not sure if my methods are optimal, but works for me.

## Method 1:

1. Do `npm pack` at root of the project, every time we make a change. This should create a file `angular2-virtual-scroll-<VERSION>.tgz` at the root
2. Then update demo project to use this. I usually uninstall `npm uni angular2-virtual-scroll` and do `npm i ../angular2-virtual-scroll-<VERSION>.tgz`. 

This method helps if you are doing specific fixes.

## Method 2:

Copy over `virtual-scroll.ts` to demo project and directly use. This method is helpful if you are doing lot of active development. When I am happy with the changes, I copy the file back to the original location.

`npm link` will not work because the component and the demo project would be referring to different copies of `@angular/core`. 

I am planning to revisit and configure this for easy setup. I will share the details if I am successful.

**Comment by tstirrat** [comment]
Thanks! I was using a variant of method 2. It would be good to find a way
to use `npm link`, it's much simpler.

**Comment by jdussouillez** [comment]
Old topic, but it would be nice to have the procedure to run/debug locally in the project's readme.
