### ISSUE TITLE
Nested ngFor

### ISSUE THREAD

**Issue by dtomaszewski** [rintoj/angular2-virtual-scroll#132]
Is it possible to make virtual scroll working for nested ngFor ? I need to make table with possibility to collapse groups.

I'm trying such simple example and all attribute items are rendered

    <virtual-scroll [items]="levels" (update)="viewPortLevels = $event">
        <div *ngFor="let group of viewPortLevels[0].groups">
            <strong>{{group.name}}</strong>

            <div *ngFor="let attribute of group.attributes">
                {{attribute.channelAttribute.name}}
            </div>
        </div>
    </virtual-scroll>

**Comment by whyboris** [comment]
This seems related: https://github.com/rintoj/angular2-virtual-scroll/issues/134

**Comment by speige** [comment]
This is not currently an officially supported feature. Would either of you be willing to attempt to code this feature & submit a pull request? Thanks.

**Comment by speige** [comment]
One issue with this is the childItems might become variable size (which we partially-support, but our implementation is naive so nested ngFor could potentially break it). A lot of that would depend on if group.attributes was read-only after the datasource is initially loaded or if it could change afterwards (we cache the calculated child item pixel dimensions for performance reasons rather than re-measuring constantly).

I think your code should work, but you have some typos. I think this seems more accurate (untested):
```
<virtual-scroll [items]="levels" (update)="viewPortLevels = $event">
    <div *ngFor="let group of viewPortLevels">
        <strong>{{group.name}}</strong>

        <div *ngFor="let attribute of group.attributes">
            {{attribute.channelAttribute.name}}
        </div>
    </div>
</virtual-scroll>
```

**Comment by speige** [comment]
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

I originally flagged this as a feature request, but on second thought, I think it might actually work with the current implementation of the component (possibly requiring the variable size child items flag to be enabled).

**Comment by speige** [comment]
Your code tells it to render all subitems at the same time. What are you hoping to achieve? A second scroller?

You could try a second virtual-scroller for the subitems to see if it works how you want. I've never tried this but I assume it'll give you a 2nd scrollbar. Nested virtual-scroller is not an officially supported option, so if it doesn't work well, you'll need to figure it out on your own. My guess is it'll feel awkward & have performance issues, but I'm not sure.

**Comment by brunobastosg** [comment]
Yeah, I was hoping for a second scroller. I added a second virtual-scroller for the subitems, like you suggested, and it kinda worked, but there were some bugs, so I ended up using pagination.

Thanks!
