### ISSUE TITLE
expand collapse

### ISSUE THREAD

**Issue by istiti** [rintoj/angular2-virtual-scroll#134]
would be nice to have expand/collapse feature (load data on click) and kepp virtual scroll, any idea? 

cc @rintoj

**Comment by istiti** [comment]
Any news about this feature ? 
actually im using this library in my project with `LOADING IN CHUNKS` feature  on a `<table>`

Sometimes we need group certains items from servers response into one `<tr>` line and click on it expand it but keep virtual scrolling working, seems actually it breaks.


cc @rintoj

**Comment by speige** [comment]
Would either of you be willing to attempt to code this feature & submit a pull request? Thanks.

**Comment by speige** [comment]
This was originally flagged as a feature request, but on second thought, I think it should actually work with the current implementation of the component. It's probably an app-specific issue & nothing wrong with the virtual-scroll component.

Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.
