### ISSUE TITLE
Module "@angular/core/index" has no exported member 'Renderer2'

### ISSUE THREAD

**Issue by JoshMarkF** [rintoj/angular2-virtual-scroll#139]
I am attempting to use this with an angular2 project.
However I am getting the error 'Module "@angular/core/index" has no exported member 'Renderer2'' every time I npm install and include the code.
As per my understanding, Renderer2 is used in Angular4, but I am relatively new to Angular.
Am I doing something wrong, or is there a fix for this issue?

**Comment by rafaelcgdf** [comment]
I'm having the same issue, 

Is there any way we can use the library with angular 2? I can't update to 4 just yet

**Comment by rdgfuentes** [comment]
I'm having the same problem. We need to update to v0.3.1 to solve the performance issue (https://github.com/rintoj/angular2-virtual-scroll/pull/117) but it seems that now Angular 4+ is mandatory and we can not upgrade our app so easily from Angular 2 to Angular 4. Is that correct @rintoj  @a139383 ?

**Comment by loctrice** [comment]
Will v0.3.1 work? I can't upgrade either. I just installed the most recent version and I'm having the same issue.

**Comment by speige** [comment]
Sorry, unfortunately this component doesn't support Angular2 anymore. It shouldn't be too hard to fork this & downgrade the package.json to an older version of Angular & fix a couple compiler errors. However, since the majority of users will be upgrading to new versions of Angular, that's probably best left to someone else to maintain.

I upgraded to v6 with the latest release without thinking about the repercussions. I'll see how far back I can downgrade to support users of older versions & update the npm package soon, but it'll probably only go back as far as v4, not v2.

Closing for now as Angular2.x is no longer supported.
