### ISSUE TITLE
it doesn't work for me when integrate with ng-lazyload-image

### ISSUE THREAD

**Issue by alsosweet** [rintoj/angular2-virtual-scroll#149]
1.npm install ng-lazyload-image@3.3.3  --save
2.
import { LazyLoadImageModule } from 'ng-lazyload-image';
...
@NgModule({
    declarations: [ AppComponent ],
    imports: [ BrowserModule, LazyLoadImageModule ],
    bootstrap: [ AppComponent ]
})
export class MyAppModule {}
3.
    <virtual-scroll
      [items]="buffer"
      (update)="scrollItems = $event"
      (end)="fetchMore($event)" #container>
      
      <div *ngFor="let item of scrollItems">
        <div><img [defaultImage]="'assets/images/git.png'" [lazyLoad]="item.url" style="height: 90px; width: 90px;" /></div>
      </div>
      <div *ngIf="loading" class="loader">Loading...</div>

    </virtual-scroll>

scroll up and down ,some img doesn't  update. Is there any other better solution?

**Comment by cjackson234** [comment]
I'm running into a very similar issue. Anyone have any tips?

**Comment by speige** [comment]
Closing since cjackson234 submitted a workaround. Also, ng-lazyload-image has documentation on how to listen for custom scroll events from custom scrollers. You will need to implement this yourself as it's not the responsibility of angular2-virtual-scroll as most users won't use it with ng-lazyload-image.

Please re-open if you have further issues.
