### ISSUE TITLE
Virtual Scroll with dynamic size

### ISSUE THREAD

**Issue by gentle9** [rintoj/angular2-virtual-scroll#155]
Hi,

is it possible to have a dynamic size of the virtual scroll container element? 
I don´t mean the childs I mean the container itself. I have a resizeable div like gridster and want to have a virtual scroll inside it. If I don´t define the size in px in CSS of virtual scroll it is not working. I have tried to set the size with % but this doesn´t work either.

Best Regards

**Comment by speige** [comment]
I believe whyboris has the correct solution.

I'm closing this since there's an existing workaround. The documentation does specifically state that a static size is needed.

This is also discussed in the documentation under "If container size changes".
You might try adding a javascript event handler for when the size changes & calling .refresh()

It seems possible to have virtual-scroll monitor for size changes automatically, rather that making the developer do it. It should be fairly easy. If either of you is interested in coding this, please submit a pull request. Thanks.

**Comment by speige** [comment]
Fyi, I've added a feature to auto-call .refresh() if the container size changes. It uses setInterval to check if clientBoundingRect on the scroll container has changed. There are a few undocumented parameters that can be changed to adjust this to meet your needs.

It's only it git so far, not npm, but should be published soon.

Let me know if it helps.
