### ISSUE TITLE
Change scrollable-content class' height from 100% to auto

### ISSUE THREAD

**Issue by Guedez** [rintoj/angular2-virtual-scroll#161]
Change scrollable-content class' height from 100% to auto
Without this, the bufferAmount property don't work.

It could be related to me using the virtual-scroll inside a flex-box, but I can't be sure of it.
I've changed it inside the node_modules/angular2-virtual-scroll/virtual-scroll.js, but I am unsure of the consequences, and probably will lose my 'fix' if I ever update the dependencies

**Comment by speige** [comment]
You will lose your changes if you update your dependencies. The correct way to do this is to fork the git repo and point your package.json directly at your github instead of npm. However, you should be able to do this with straight CSS without changing any code in the package.

If you'd like to have this officially added to the repo, please submit a pull request. I'm a little nervous that it might have unintended consequences for other users with different setups, so it'll need to be thoroughly tested with various scenarios.

Closing this for now. Please re-open if needed.
