### ISSUE TITLE
Scroll bars cannot slide!!!

### ISSUE THREAD

**Issue by DongFangMingLiang** [rintoj/angular2-virtual-scroll#162]
![image](https://user-images.githubusercontent.com/22604816/34405369-f9bf740a-ebed-11e7-8b86-9df6912d9706.png)
**When I execute the code on top of the two quickly
The scroll bar can't roll properly**

**Comment by speige** [comment]
This is because virtualScroll cannot easily monitor if the array has changed.

There's a new version on npm which does a slightly better job of monitoring these changes, please update to it.

Also, please add

```
this.virtualScroll.refresh();
```
before this.virtualScroll.scrollInto

or
```
setTimeout(() => { this.virtualScroll.scrollInto(item); }, 0);
```

Closing this for now. Please re-open if you continue to have issues.
