### ISSUE TITLE
using table rows for list item

### ISSUE THREAD

**Issue by Taifuru** [rintoj/angular2-virtual-scroll#17]
Hi can i use table as list-items ? If i can can you show me i pseudo code ?

**Comment by rintoj** [comment]
The following should help you. Make sure to set fixed height for `tbody` and `table`
```
<table>
  <thead>
    <tr>
      <th>Column 1</th>
      <th>Column 2</th>  
      <th>Column 3</th> 
    </tr>
  </thead>
  <tbody>
    <virtual-scroll [items]="items" (update)="viewPortItems = $event">
      <tr *ngFor="let item of viewPortItems">
         <td>{{item.colomn1}}</td>
         <td>{{item.colomn2}}</td>
         <td>{{item.colomn3}}</td>
      </tr>
    </virtual-scroll>
  </tbody>
</table>
```

**Comment by PillowPillow** [comment]
From my experience, you can't do something like that since virtual scroll add block elements to the dom. 
If you wanna use a table with this library you have to declare the table inside the virtual-scroll element. Unfortunately that remove the possibility to use a fixed header without doing tricky things.

**Comment by matte00** [comment]
@PillowPillow you are right man!
