### ISSUE TITLE
CTRL + F not working in virtual list

### ISSUE THREAD

**Issue by vaibhav2009** [rintoj/angular2-virtual-scroll#182]
Let me explain it with an example-Suppose I am having a list of say ten thousand data and I want to use search in the page( i.e. ctrl +f) functionality of browser to search data that might be present at the end of the list. So, using ctrl+f to search that data is not working on the list.

**Comment by lunchboxsuhi** [comment]
It wont work due to the fact that the data is not present in the DOM. The virtual list does not render the data, it only renders X of Y, where X is the items displayed and Y being the total. Generally it only shows between 10-15 items, those items can be found by the browser using `ctrl+f`. An easy work around is to add a text field that will filter the list down based on the items.

**Comment by vaibhav2009** [comment]
I don't want to disable default CTRL+F behavior of the browser, so is there any way to catch the keys input in Ctrl+f dialog box? so that, I can try to search the keys in my list that is not rendered in the DOM and populate them accordingly.

**Comment by lunchboxsuhi** [comment]
Unfortunately every browser implementation for `ctrl+f` is different. To my understanding the API lacks quite a bit. Realistically the browser find feature is great but you need to think of this component similar to a pagination object where only so much is visible to the client at a time. 

Having a specific search bar integrated within your app is the best approach overall because not everyone who will use your web app will know what ctrl+f is. 

Sorry I can't be more helpful, only other issues is if your heart is still set on it, it will be a pretty big piece since Edge, Firefox and Chrome all have their own API and not a standard one for ctrl+f if my understanding is correct. I remember chrome had an open issue to make ctrl+f function similar to Firefox but there was too many issues during its Development.
