### ISSUE TITLE
2 types of component keep blinking

### ISSUE THREAD

**Issue by Liork1** [rintoj/angular2-virtual-scroll#196]
Hi,

I'm trying to use virtual scroller with 2 `different` types of compnents.
I mean, I need to present 1 virtual list combined with 2 types of items.

The code looks like this:
`    
<virtual-scroll [items]="buffer" (update)="scrollItems = $event"
            (change)="onListChange($event)">

            <div *ngFor="let item of scrollItems" [item]="item"> 

                <div *ngIf="item.type == 1">type 1</div>
                <div *ngIf="item.type == 2">type 2</div>

          </div>

   </virtual-scroll>`

as a result the scroller keep blinking and nothing being displayed.

any way to do it?

**Comment by Liork1** [comment]
Found a solution

**Comment by gklasen** [comment]
Glad you shared your solution.

**Comment by pcsantana** [comment]
@Liork1 how did you fixed? I'm facing a similar problem.

Thank you!

**Comment by speige** [comment]
If each array index will display both item types next to each other, you
could try wrapping them in a parent tag.

If only 1 child per array index, but the child type is different for each
index, you could try the the enableUnequalChildrenSizes flag.

If only 1 child per array index and all indexes are the same child type,
you could create 2 separate virtual-scoll, 1 for each child type & put the
*ngIf on the virtual-scroll instead of the children.

**Comment by pcsantana** [comment]
Thank you @speige !
Actually I was making a mistake.
I had a condition to not show a custom div if it is the first item. So I put:
```
<div *ngFor="let item of viewPortItems; let i = index">
    <div *ngIf="item.isFirst && i != 0">
    ...
    </div
</div>
```
But I realized that it´s recycled and always the view in the top is index == 0, so the scroll jumps when that view recycled. 
Removing the ``` i != 0 ``` solved my problem.

Anyway, thank you for the suport.
