### ISSUE TITLE
could you please make private props and methods protected to allow extend them?

### ISSUE THREAD

**Issue by MariMax** [rintoj/angular2-virtual-scroll#199]
my case: I don't know all the items, I know few of them upfront and I know the number of items, my idea is to extend your component and set proper height for the scroll, add empty template for item, which will represent fetching process when user for example drag scrollbar into the middle of the list and I don't have all the items to show.
Unfortunately I cannot do 
```
export class ExtendedVirtualScrollComponent extends VirtualScrollComponent
```
in current implementation 
I can copy paste your component, but it's not the right way

**Comment by speige** [comment]
Sure. Would you mind submitting a pull request?

**Comment by speige** [comment]
The correct code in github uses protected everywhere instead of private. It's not yet published to npm. Closing for now. Please re-open if that doesn't solve your issue.

Also, I wonder if you really need to extend the control. Maybe what you desire can be done with the existing component? If not, let's brainstorm the feature you need & see if it can be created. Thanks.
