### ISSUE TITLE
BUG infinite request on (change)

### ISSUE THREAD

**Issue by istiti** [rintoj/angular2-virtual-scroll#20]
I succed to use your module, FINALLY ! :)

I simply use your demo  to load more chunk when scrolling but it seems big bug when scroll fast or drag scrollbar until bottom, look here my gif: 

![bug chunk load](https://cloud.githubusercontent.com/assets/2789203/22934401/18f95a8e-f2cf-11e6-86a1-5519e3da7cfe.gif)

## code: 
exactly the same  as your demo 

## browser: 
bug on chrome and firefox

**Comment by rintoj** [comment]
Related to #19. Working on it.

**Comment by istiti** [comment]
Nice, i cant wait !!! :-D

**Comment by gnasit** [comment]
the way I have worked around this is only do the next fetch of chunk when I have not requested the previous starting point in chunk...

to elaborate, i created a set of values going into the below method, if my set size increases while while adding the element to the set, then i call the below, else i don't fetch the next chunk.

`this.fetchNextChunk(this.buffer.length, 10)`

this has worked for me, in not fetching duplicates. hope this gives some ideas to avoid the duplication, until it is fixed in the library by rintoj.

good work otherwise Rintoj! thanks!

**Comment by rintoj** [comment]
@istiti, @gnasit, Thanks for helping me with this issue. I have added two new events: `start` and `end`. Recommend you to use `end` instead of `change`. 

Please see the updated [documentation](https://github.com/rintoj/angular2-virtual-scroll#loading-in-chunk)

**Comment by rintoj** [comment]
Fix is available with v0.1.3
