### ISSUE TITLE
scrollToIndex with animationMilliseconds doesn't animate

### ISSUE THREAD

**Issue by denkan** [rintoj/angular2-virtual-scroll#220]
Great module!

Tried to use `scrollToIndex` with custom value for `animationMilliseconds`. Didn't animate as expected (at all).

Checked the source and found the retry `retryIfNeeded()` fires the method with `animationMilliseconds=0`. 

https://github.com/rintoj/angular2-virtual-scroll/blob/78bdd79ba79a0efc9ff2aa556f7109da2c2908da/src/virtual-scroll.ts#L329

Why is that? 
If I change to the `animationMilliseconds` variable, it works as expected.

**Comment by speige** [comment]
It works correctly on all the demos at http://rintoj.github.io/angular2-virtual-scroll. I believe the component code is correct & it's something wrong with your app. Please submit a stackblitz if you need help troubleshooting.

If you look at the sourcecode, scrollToIndex calls scrollToIndex_internal 2x, the retry portion is hard-coded to 0, but the original call uses the animationMilliseconds parameter.

The retry is used in case the 1st auto-scroll went to the wrong location. This can happen if you use [enableUnequalChildrenSizes]="true" because the child items aren't pre-measured, they're estimated & measured in realtime while scrolling. The estimates are usually pretty close & the retry should instantly snap to the correct place at the end of the animation. If we used the the animationMilliseconds parameter during the retry the total animation would take 2x as long as intended.

**Comment by speige** [comment]
Closing since I haven't heard back from the original poster & it seems like user error. Please re-open if you continue to experience issues.

**Comment by mernen** [comment]
I had the same problem. In my case, another dependency was using Tween.js v16, while ngx-virtual-scroller uses v17. The build process only included one copy (v16) of the library, and there's a slight change on its `onUpdate()` callback. I managed to work around this issue by updating this other dependency to get rid of Tween.js v16.
