### ISSUE TITLE
Retain current scroll position when chunked items are concatenated to the top of list, chat behavior

### ISSUE THREAD

**Issue by shajeeck** [rintoj/angular2-virtual-scroll#223]
Thanks for this great virtual scroll.

Is there any way to maintain the current scroll position when chunked items are concatenated to the top the list? this is a usual chat behavior, when reaching top of the scroll list

`this.buffer = chunk.concat(this.buffer)` the reverse in your doc [new data on top]

current behavior will replace the viewport items instead of adding it to the top and maintaining current scroll position!

**Comment by speige** [comment]
This is not a built-in feature, but you can code it easily yourself.
The virtual-scroll has an API with methods such as scrollInto or scrollToIndex which you can use. You'll need to figure out when to call it & what value to use.
My suggestion is to store the most recent value for the "start" from the virtual-scroll before modifying the list & then calling scrollToIndex afterwards.
You can get the most recent "start" index from the change/start events (or get it directly from the viewPortIndices property)
Since you're adding extra items to the list you'll probably want countNewItems+originalStartIndex

One caveat is if you're using enableUnequalChildrenSizes, the startIndex property is confusing. It's related to bug #209
You'll need to call scrollToIndex with desiredIndex+virtualScroll.bufferAmount to fix it.

Also, after adding the new items you may need wait momentarily before calling scrollToIndex to give it time to recalculate the new items, something like setTimout(, 0).

If you want to modify the source code to make this a first-class feature, I'm happy to accept a pull request.
Thanks.

**Comment by speige** [comment]
Also, you could try doing buffer.unshift or buffer.splice to modify the array directly (you may need to call virtualScroll.refresh afterwards in-case angular doesn't automatically rebind). I'm guessing this still won't maintain the current scroll position, but I haven't tested it, so maybe it's worth trying.

**Comment by shajeeck** [comment]
I will try these and and update, will close this issue for now as this feature is not intended to be added from your side. Will open new if any promising updates from my end.

Thanks

**Comment by jonnyleeharris** [comment]
> I will try these and update, will close this issue for now as this feature is not intended to be added from your side. Will open new if any promising updates and PR from my end.
> 
> Thanks

Hey, just wondering how you finally solved this one. I am dealing with a similar use case and am using different sized items with the `enableUnequalChildrenSizes` flag , I have managed to get the scroll position to stay (roughly) the same - but there is still some jitter:

      let startIndex = this.chatMessagesScroller.viewPortInfo.startIndex;
      let count = newItems.length;
      this.list = newItems.concat(this.list);      
      this.chatMessagesScroller.scrollToIndex(startIndex+count,false,0,0);
