### ISSUE TITLE
CHANGE event conflicts. When virtual scroll is used with other controls, CHANGE event will pop up the events of other controls

### ISSUE THREAD

**Issue by Anberm** [rintoj/angular2-virtual-scroll#225]
![virtual-scroll](https://user-images.githubusercontent.com/34148806/44614354-75646380-a855-11e8-881a-7b1ccdc77d54.gif)
https://stackblitz.com/edit/angular-dqe6az?file=src/app/app.component.ts

I use virtual-scroll with table and input-number. Change event pops up {start: 0, end: 11} when I scroll, but change event pops up {isTrusted: true} when I change input-number value

**Comment by speige** [comment]
It appears this is a known issue of Angular2 caused by DOM event bubbling. I've coded a fix for this by prefixing the event names with vs*. So, you can use (vsChange)="" instead of (change)=""

It's been committed to git. Should be in npm soon.

Please re-open if you don't think this will resolve your issue.

**Comment by speige** [comment]
Link to known Angular2 issue: https://github.com/angular/angular/issues/13997

**Comment by speige** [comment]
Version 0.4.10 is now on npm. Please test it & re-open if your issue persists.
