### ISSUE TITLE
parentScroll

### ISSUE THREAD

**Issue by misha2011** [rintoj/angular2-virtual-scroll#228]
Please update documentation for  [parentScroll],
was [parentScroll]="scrollingBlock.nativeElement" becoming [parentScroll]="scrollingBlock"

**Comment by speige** [comment]
Good catch. I'll do this.

However, the documentation isn't completely wrong.

These are both valid:
```
<random-angular-component #element1>
    <virtual-scroll [parentScroll]="element1.nativeElement">
    </virtual-scroll>
</random-angular-component>
```

```
<div #element2>
    <virtual-scroll [parentScroll]="element2">
    </virtual-scroll>
</div>
```

The issue is that parentScroll must be assigned a native javascript DOM element reference. the angular #elementRef syntax will give you a different javascript variable type based on the type of element. If it's a native HTML element such as a DIV, it'll give you a native javascript DOM element reference. If it's a custom angular component, the DOM element will be wrapped in an Angular ElementRef https://angular.io/api/core/ElementRef in which case you'll need to call .nativeElement to get to the javascript DOM element reference.

**Comment by speige** [comment]
I've updated the documentation based on your request. Please re-open if this is still incorrect.
