### ISSUE TITLE
Multiple Virtual Scroll and FlexBox

### ISSUE THREAD

**Issue by amirsaber** [rintoj/angular2-virtual-scroll#27]
First of all I want to thank you for your nice module.
I am trying to implement your module in my project but I have difficulty with two things
1. I can't manage to have multiple virtual scroll in one page. It seems some how they are repeating the same items which is the items of the last virtual scroll
2. I am using [Angular Flex Layout](https://github.com/angular/flex-layout) to size my items in the virtual scroll but it seems it doesn't detect the child size. Any recommendation?

**Comment by rintoj** [comment]
@amirsaber, thank you. I'm glad you like this component.

Regarding the difficulties you are facing:

1. This is unlikely. Please checkout my [demo page](http://rintoj.github.io/angular2-virtual-scroll/index.html). You can see multiple virtual-scrolls working independently. I ran some tests as well; all looked well here. I'm assuming it is caused by an error in your code. If you can share the code, I would be glad to look at it.

2. I use `getBoundingClientRect()` (see [here](https://github.com/rintoj/angular2-virtual-scroll/blob/master/src/virtual-scroll.ts#L150)) to calcuate child's size. I wasn't able to see a scenario where this failed. However the calculation may fail temporarly if container's size or the children's side itself is changed. This will get auto corrected when user start to scroll again or you could call `refresh()` method to fix it.

**Comment by amirsaber** [comment]
thanks for your reply. I am trying to reproduce the issue that I am facing and share it with you, meanwhile I thought maybe sharing my scenario might help:
I have an ngFor over the virtual-scroll and every time I am passing a new set of array to ng-for. It seems in your examples you are using same array in all of virtual-scrolls. I face the issue when I supplly different arrays into virtual scroll within a ngFor.

**Comment by amirsaber** [comment]
I figured them out. If you put multiple virtual-scroll on same component for different arrays with same name for items(viewportitems) you will get this issue. Also about flexbox, since the structure of the app changes to scrollable-content div with the repeated items in as childs, the flexbox layout you imagine when coding and the one that you get on browser are different

**Comment by maku** [comment]
@amirsaber Do you have an example how to use it with Angular Flex Layout. I am not able to get it working.... TIA
