### ISSUE TITLE
viewport items not updating when items sorted.

### ISSUE THREAD

**Issue by prosenjit-itobuz** [rintoj/angular2-virtual-scroll#44]
Say I use a sort function, and I call the refresh fn. The data in view does not update. But as soon as I scroll once, the data in viewport gets updated. I tried, using `virtualScroll.contentElementRef.nativeElement.scrollTop += 1`, but that doesnt work as well.

Can you please help?

**Comment by rintoj** [comment]
@prosenjit-itobuz, I'm assuming that you would have done the following to sort the list:

```ts
this.list.sort()
```

The trouble you are facing is due to non-immutable operation. Sorting is not an immutable operation, meaning it changes the array itself instead of creating a new one. The below code fix that.

```ts
this.list = [].concat(this.list).sort();
```

I have updated the live samples as well. You can see this in action here: http://rintoj.github.io/angular2-virtual-scroll/index.html#samples

![image](https://cloud.githubusercontent.com/assets/10824903/26032316/ebcd4ee2-38ad-11e7-8824-eb16c64db3f8.png)

**Comment by prosenjit-itobuz** [comment]
Thanks it's working.
