### ISSUE TITLE
About `end` event

### ISSUE THREAD

**Issue by tolemac** [rintoj/angular2-virtual-scroll#54]
Hi @rintoj, 

what do you think about fire `end` event at startup if all elements are showed?

I'm using `end` event to load more items from a service, I load elements in groups of 10 items, however if the viewPort show the 10 firsts items without show scrollbar the `end` event never trigger.

What do you think about? Is this way by design?

If you are agree I could make a pullrequest ;)

**Comment by ourarash** [comment]
@tolemac Did you find any solution for this? I don't get the end event either.

**Comment by tolemac** [comment]
I'm not sure now, I stopped use it due to I have diferents heights in my rows.

I have been looking, and I have my own versión, the diference with the original is:

Change that:
````typescript
      // emit 'end' event
      if (end !== this.previousEnd && this.startupLoop === false) {
        this.end.emit({ start, end });
      }
````

For that:
````typescript
            // emit 'end' event
            if ((end !== this.previousEnd && this.startupLoop === false) || end === items.length) { 
                this.end.emit({ start, end });
            }
````

Try it and tell me ;)

**Comment by sam-lex** [comment]
I encountered the same problem, but took me longer to identify it, in my case it was barely showing all the items, so it had a little scroll, and my `change` event wasn't being called until I resized... but anyways, I solved like this:

on `onInit` I fetch the initial data, once it completes, I wait for about `100ms` using `setTimeout` (waiting for it to render the elements etc.. otherwise `.previousEnd` will be like.. `0.. 2...3..`) and check if the initial data are all visible with `virtualScroll.previousEnd === chunkSize` (I could use the length also)... If it is, then I fetch the next chunk. This is working well so far

```typescript
@ViewChild(VirtualScrollComponent)
private virtualScroll: VirtualScrollComponent;

private chunkSize: number = 20;

ngOnInit() {
  this._updateCount();
  this.saleService.find( this.currentChunk )
    .takeUntil( this.ngUnsubscribe )
    .subscribe(
      (data) => this.sales = data,
      (err) => console.log('err fetching sales, ', err),
      () => this.loadNextIfNecessary()
    );
}

private loadNextIfNecessary() {
  setTimeout(() => {
    if (this.virtualScroll.previousEnd === this.chunkSize)
      this.fetchNextChunk();
  }, 100);
}
```

**Comment by speige** [comment]
@tolemac Please submit a pull request for your requested change if you think it'll be useful to other users. Also, I will be merging the dynamic-height-child-items PR soon, so that might help resolve your other issues (although it sounds like you've already moved onto a new component).

**Comment by tolemac** [comment]
@speige too late, I don't remember where is the code.
sorry

**Comment by speige** [comment]
The code now emits a `start`,  `end`, and `change` event for the 1st time the items are loaded. This should resolve the issue. Closing for now. Please re-open if you're still having issues. Thanks.
