### ISSUE TITLE
Request : compatibily with html table

### ISSUE THREAD

**Issue by johaven** [rintoj/angular2-virtual-scroll#90]
It would be great to apply virtualscroll to a table.
For the moment, it seems to be impossible : https://github.com/rintoj/angular2-virtual-scroll/issues/51

**Comment by MastaBleh** [comment]
People like you are puting the world in fire.

Raising an issue because 'it seems impossible' to do something...
We are so happy that #90 is a completly new unrelated ticket, absolutly not the exact same thing as #51.

It seems that you are ... dosgijdfogfjdfg
qdf
godkqgfqd
fgkqd
^gfkdo
qfgo^ko

Close this ticket; read #51; make it work. Or explain exactly what is your problem with ts & html snippet in #51

**Comment by MastaBleh** [comment]
content of answer : okay
form of answer: jerk

everybody agreed, so get focused on content.
