### ISSUE TITLE
scrollInto method displays selected element at bottom of view

### ISSUE THREAD

**Issue by simianarmy** [rintoj/angular2-virtual-scroll#91]
I have a sample size of 10K fixed-height elements in 100-element buffer and everything seems to work fine.
My only complaint is that when I call scrollInto() with a target element, I would like it to display at the top of the viewport, not the bottom!
It would be nice to have an option to pass into scrollInto that could specify the position of the item, such as TOP, CENTER, or BOTTOM.

**Comment by speige** [comment]
Strange, I believe scrollInto usually aligns to the top of the viewport. Can you submit a code sample or stackblitz to help troubleshoot this?

I agree that a position parameter for scrollInto would be very valuable. If you have time to code it, I'm happy to merge your pull request. Thanks.

**Comment by speige** [comment]
It appears there was a past issue where it was aligning to bottom instead of top, but it was resolved through a pull request. I'm guessing you were using the version before that merge was completed. Please try with the newest version. Closing for now. Feel free to re-open if you're still having issues. Thanks.

**Comment by speige** [comment]
I've added a bool parameter for alignToBeginning to the scrollInto method. I didn't think about "center", oops. It's not yet on npm, just git, but should be published soon. Let me know if it helps. Thanks.
